name = "GeneticProgramming"
uuid = "ad102508-34d1-48cc-9d5a-825d0c17f2b5"
authors = ["Daniel Rivero"]
version = "1.0.0"

[deps]
JLD2 = "0.4.38"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
